<a href="https://colab.research.google.com/github/Lacchi1234/machinelearning_1/blob/main/iris_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import datasets

In [3]:
iris=datasets.load_iris()
x=iris.data
y=iris.target

In [4]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [5]:
res=DecisionTreeClassifier()
res.fit(x_train,y_train)

DecisionTreeClassifier()

In [6]:
y_predict=res.predict(x_test)
y_predict



array([0, 1, 0, 2, 1, 1, 0, 2, 2, 1, 2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 1, 0, 2])

In [7]:
y_test

array([0, 1, 0, 2, 1, 1, 0, 2, 1, 1, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 1, 0, 1])

compare y_test and y_pred, that gives the accuracy//


In [8]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,y_predict)


0.9

In [9]:
print("confusion_matrix: ",confusion_matrix(y_test, y_predict))
print("classification_report:")
print(classification_report(y_test, y_predict))

confusion_matrix:  [[12  0  0]
 [ 0  5  3]
 [ 0  0 10]]
classification_report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.62      0.77         8
           2       0.77      1.00      0.87        10

    accuracy                           0.90        30
   macro avg       0.92      0.88      0.88        30
weighted avg       0.92      0.90      0.89        30

